### ISSUE TITLE
VEF Breaks Vanilla's Mechanism for Repairing Drug Policies

### ISSUE THREAD

**Issue by brucethemoose** [AndroidQuazar/VanillaExpandedFramework#6]
When removing a mod from an existing save that adds new drugs, vanilla Rimworld will clean up the drug policies containing the old drugs:

https://gist.github.com/HugsLibRecordKeeper/11863c0257e457949e78305c7bc920a1#file-output_log-txt-L109

But when VEF is loaded, the old drug policies don't get cleaned up, and the game spams the log:

https://gist.github.com/HugsLibRecordKeeper/34fe164cefd381d518bd3ebdaaef635c#file-output_log-txt-L227

**Comment by juanosarg** [comment]
@OrionFive 
Take a look at this!

**Comment by OrionFive** [comment]
@brucethemoose Generally, removing mods mid-game is not something any mod actively supports.
But because I apparently have time over, I made an attempt at a fix that you get to try out.
So please [download this](https://github.com/AndroidQuazar/VanillaExpandedFramework/archive/312e6cd09ad2cb56bceb4e036df05678e2ee91ef.zip), make sure it loads the local and not the steam version (mod manager?) and check if it solves the issue.

If not, a new log would be useful.
